-- Creación de la base de datos
CREATE DATABASE INOVATEC
GO

USE INOVATEC
GO

-- Creación de Tablas
CREATE TABLE ALUMNO (
	NO_CONTROL int PRIMARY KEY,
	NOM varchar(20),
	AP varchar(20),		--NOM + AP + AM = NOMBRE
	AM varchar(20),
	SEMESTRE int,
	CARRERA varchar(50),
	CONSTRAINT DOM_NO_CONTROL CHECK(NO_CONTROL >= 0 AND NO_CONTROL <= 99999999),
	CONSTRAINT DOM_AP CHECK(AP like'%[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz]'),
	CONSTRAINT DOM_AM CHECK(AM like'%[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz]'),
	CONSTRAINT DOM_SEMESTRE CHECK(SEMESTRE >= 0 AND SEMESTRE <= 99999999),
)
GO

CREATE TABLE PROYECTO (
	NOM_PROYECTO varchar(40),
	ANIO int,
	NUM_PROYECTO int,
	ASESOR_1 varchar(100),
	ASESOR_2 varchar(100),
	ASESOR_3 varchar(100),
	CONSTRAINT CLAVE_P PRIMARY KEY(ANIO, NUM_PROYECTO),		--ANIO + NUM_PROYECTO = CLAVE_P
	CONSTRAINT DOM_ANIO CHECK(ANIO >= 0 AND ANIO <= 9999),
	CONSTRAINT DOM_NUM_PROYECTO CHECK(NUM_PROYECTO >= 0 AND NUM_PROYECTO <= 99999999),
)
GO

CREATE TABLE CONCURSO (
	ID_CONCUR bigint identity(1,1),
	NO_CONTROL1 int FOREIGN KEY REFERENCES ALUMNO(NO_CONTROL),
	NO_CONTROL2 int FOREIGN KEY REFERENCES ALUMNO(NO_CONTROL),
	NO_CONTROL3 int FOREIGN KEY REFERENCES ALUMNO(NO_CONTROL),
	ANIO int,
	NUM_PROYECTO int,
	LUGAR_OB int,
	ETAPA varchar(20),
	CATEGORIA varchar(20),
	FOREIGN KEY (ANIO, NUM_PROYECTO) REFERENCES PROYECTO (ANIO, NUM_PROYECTO),
	CONSTRAINT DOM_NO_CONTROL1 CHECK(NO_CONTROL1 >= 0 AND NO_CONTROL1 <= 99999999),
	CONSTRAINT DOM_NO_CONTROL2 CHECK(NO_CONTROL2 >= 0 AND NO_CONTROL2 <= 99999999),
	CONSTRAINT DOM_NO_CONTROL3 CHECK(NO_CONTROL3 >= 0 AND NO_CONTROL3 <= 99999999),
	CONSTRAINT DOM_CATEGORIA CHECK(CATEGORIA like'%[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz]'),
	CONSTRAINT DOM_ETAPA CHECK(ETAPA like'%[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz]'),
	CONSTRAINT DOM_LUGAR_OB CHECK(LUGAR_OB >= 0 AND LUGAR_OB <= 10)
)
GO

-- Inserción de valores en ALUMNO
INSERT INTO ALUMNO (NO_CONTROL, NOM, AP, AM, SEMESTRE, CARRERA)
VALUES (22290831, 'Daniel', 'Díaz', 'Larios', 5, 'Ingeniería en Sistemas Computacionales')

-- Inserción de valores en PROYECTO
INSERT INTO PROYECTO (ANIO, NUM_PROYECTO, NOM_PROYECTO, ASESOR_1, ASESOR_2, ASESOR_3)
VALUES (2024, 20, 'Sistema de Riego', 'Juan Alberto', 'Ramiro Sánchez', 'Juan Alonso')

-- Inserción de valores en CONCURSO
INSERT INTO CONCURSO (LUGAR_OB, ETAPA, CATEGORIA, NO_CONTROL1, ANIO, NUM_PROYECTO)
VALUES (2, 'Inicial', 'Ciencias Básicas', 22290831, 2024, 21)

-- Consultar datos
SELECT * FROM ALUMNO;
SELECT * FROM PROYECTO;
SELECT * FROM CONCURSO;

-- Eliminar Base de Datos
USE master
DROP DATABASE INOVATEC
