--CÓDIGO PARA MYSQL

-- Creación de la base de datos
CREATE DATABASE INOVATEC;

--Usar la base de datos
USE INOVATEC;

-- Creación de Tablas
CREATE TABLE ALUMNO (
	NO_CONTROL int PRIMARY KEY,
	NOM varchar(20),
	AP varchar(20),
	AM varchar(20),
	SEMESTRE int,
	CARRERA varchar(50),
	CONSTRAINT DOM_NO_CONTROL CHECK(NO_CONTROL >= 0 AND NO_CONTROL <= 99999999),
	CONSTRAINT DOM_SEMESTRE CHECK(SEMESTRE >= 0 AND SEMESTRE <= 99999999)
);

CREATE TABLE PROYECTO (
	ANIO int,
	NUM_PROYECTO int,
	NOM_PROYECTO varchar(40),
	ASESOR_1 varchar(100),
	ASESOR_2 varchar(100),
	ASESOR_3 varchar(100),
	CONSTRAINT CLAVE_P PRIMARY KEY(ANIO, NUM_PROYECTO),
	CONSTRAINT DOM_ANIO CHECK(ANIO >= 0 AND ANIO <= 9999),
	CONSTRAINT DOM_NUM_PROYECTO CHECK(NUM_PROYECTO >= 0 AND NUM_PROYECTO <= 99999999)
);

CREATE TABLE CONCURSO (
	ID_CONCUR int AUTO_INCREMENT PRIMARY KEY,
	ANIO int,
	NUM_PROYECTO int,
	NO_CONTROL1 int,
	NO_CONTROL2 int,
	NO_CONTROL3 int,
	LUGAR_OB int,
	ETAPA varchar(20),
	CATEGORIA varchar(20),
	CONSTRAINT FK_CONCURSO_CLAVE_P FOREIGN KEY (ANIO, NUM_PROYECTO) REFERENCES PROYECTO(ANIO, NUM_PROYECTO),
	CONSTRAINT DOM_NO_CONTROL1 CHECK(NO_CONTROL1 >= 0 AND NO_CONTROL1 <= 99999999),
	CONSTRAINT DOM_NO_CONTROL2 CHECK(NO_CONTROL2 >= 0 AND NO_CONTROL2 <= 99999999),
	CONSTRAINT DOM_NO_CONTROL3 CHECK(NO_CONTROL3 >= 0 AND NO_CONTROL3 <= 99999999),
	CONSTRAINT DOM_LUGAR_OB CHECK(LUGAR_OB >= 0 AND LUGAR_OB <= 10)
);

-- Inserción de valores en ALUMNO
INSERT INTO ALUMNO (NO_CONTROL, NOM, AP, AM, SEMESTRE, CARRERA)
VALUES (22290831, 'Daniel', 'Diaz', 'Larios', 5, 'Ingenieria en Sistemas Computacionales');

-- Inserción de valores en PROYECTO
INSERT INTO PROYECTO (ANIO, NUM_PROYECTO, NOM_PROYECTO, ASESOR_1, ASESOR_2, ASESOR_3)
VALUES (2024, 20, 'Sistema de Riego', 'Juan Alberto', 'Ramiro Sánchez', 'Juan Alonso');

-- Inserción de valores en CONCURSO
INSERT INTO CONCURSO (ANIO, NUM_PROYECTO, NO_CONTROL1, LUGAR_OB, ETAPA, CATEGORIA)
VALUES (2024, 20, 22290831, 3, 'Inicial', 'Mayor');

-- Consultar datos
SELECT * FROM ALUMNO;
SELECT * FROM PROYECTO;
SELECT * FROM CONCURSO;

-- Eliminar Base de Datos
--USE master
--DROP DATABASE INOVATEC
